export class SilabasCastillano {

    silables:string[] = [
        'bo',
        'ca',
        'che',
        'co',
        'cu',
        'da',     
        'de',
        'do',
        'fo',
        'ga',
        'go',
        'la',
        'lu',
        'lla',
        'llo',
        'ma',
        'na',
        'ña',
        'ni',
        'no',
        'o',
        'pa',
        'pe',
        'pi',
        'po',
        'ra',
        'ro',
        'sa',
        'so',
        'ta',
        'to',
        'u',
        'va',
        'yo'
    ];

    words = [
        // ['si','lla'], // solo un 'si'
        // ['que','so'], // solo un 'que'
        // ['yo','yo'], // solo aparecera una vez
        // ['li','ma'], // solo un li
        // ['ne','na'], // solo un 'ne'
        // ['lo','ro'], // solo un 'lo'
        // ['me','sa'], // solo un 'me'
        // ['co','co'], // solo aparecera una vez
        // ['ma','ma'], // solo aparecera una vez
        ['o','so'],
        ['u','va'],
        ['lu','na'],
        ['de','do'],
        ['ni','ña'],
        ['ro','sa'],
        ['fo','co'],
        ['ca','sa'],
        ['ga','to'],
        ['va','ca'],
        ['bo','ca'],
        ['bo','ta'],
        ['ca','ma'],
        ['cu','bo'],
        ['do','na'],
        ['fo','ca'],
        ['go','ma'],
        ['ma','no'],
        ['ma','go'],
        ['o','lla'],
        ['lla','ma'],
        ['pi','pa'],
        ['pa','to'],
        ['pi','ña'],
        ['u','ña'],
        ['po','llo'],
        ['so','pa'],
        ['to','ro'],
        ['ro','to'],
        ['va','so'],
        ['ma','sa'],
        ['la','ta'],
        ['ro','pa'],
        ['ga','llo'],
        ['sa','po'],
        ['cu','na'],
        ['da','do'],
        ['co','che'],
        ['co','do'],
        ['ma','pa'],
        ['ni','do'],
        ['o','ro'],
        ['pa','la'],
        ['pa','sa'],
        ['pa','ta'],
        ['pi','so'],
        ['ro','to'],
        ['ta','co'],
        ['co','pa'],
        ['co','la'],
        ['co','ro'],
        ['co','sa'],
        ['da','ma'],
        // ['do','ña'],
        ['fo','to'],
        ['go','ta'],
        ['la','va'],
        ['ma','lla'],
        ['no','che'],
        ['pe','ra'],
        ['pe','sa'],
        ['pi','la'],
        ['ra','yo'],
        ['sa','co'],
        ['yo','ga'],
        // sigue ora si
        ['ca','ña'],
        ['ca','ra'],
        ['co','no'],
        ['la','go'],
        ['la','na'],
        ['lu','pa'],
        ['lu','pe'],
        ['lla','no'],
        ['ma','ni'],
        ['ma','ta'],
        ['na','ta'],
        ['o','ca'],
        ['o','la'],
        ['pa','co'],
        ['pe','ña'],
        ['pe','so'],
        ['pi','co'],
        ['ra','ma'],
        ['ra','ta'],
        ['ro','ca'],
        ['ro','co'],
        ['ro','llo'],
        ['so','ga'],
        ['ta','che'],
        ['ta','llo'],
        ['to','pe']
    ];
}
// unwritten automated test: that all silables in SilabasCastillano.words arrays are present in SilabasCastillano.silables